### ISSUE TITLE
sdet-technical test urgent query

### ISSUE THREAD

**Issue by sekharpotru** [ComparetheMarket/sdet-technical-tests#2]
Hi there,

I am completing this test as a part of interview process. I see it's mentioned as tests should only proceed as far as the price results page. What are the things i need to validate on results page? Currently i am validating whether results page title "Your results" and subheading "Recommended tariffs for you" appears or not. Is it enough or do i need to validate other info like input user gives and filters available ..... etc ?

Please kindly get back to me ASAP.

Many thanks in advance.

Best regards,
Sekhar Potru,
Email : sekharPotru.SQA@hotmail.com

**Comment by AndyBarnettCTM** [comment]
Hi Sekhar,

That's a good question. We don't have specific requirements for what exactly is tested in your tech test, it's up to you to decide. This is an opportunity for you to show us the skills you have, so choose whatever solutions you think will do that! 

Hope that's answered your concerns,
~Andy

**Comment by sekharpotru** [comment]
Hi Andy,

Thanks for your swift response. Yes i got your point. 

Cheers,
Sekhar
